# Generated by Django 6.1 on 2026-08-11 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoría de recurso',
                'verbose_name_plural': 'categorías de recursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_recurso', to='inventario.categoriarecurso', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'tipo de recurso',
                'verbose_name_plural': 'tipos de recursos',
                'ordering': ('categoria__nombre', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, verbose_name='código interno')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='número de serie')),
                ('anio_fabricacion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='año de fabricación')),
                ('estado_operativo', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio'), ('dado_baja', 'Dado de baja')], default='operativo', max_length=20, verbose_name='estado operativo')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('reservado', 'Reservado'), ('no_disponible', 'No disponible')], default='disponible', max_length=20, verbose_name='disponibilidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='instituciones.estacion', verbose_name='estación')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='inventario.tiporecurso', verbose_name='tipo de recurso')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ('estacion__nombre', 'codigo_interno'),
            },
        ),
        migrations.AddConstraint(
            model_name='tiporecurso',
            constraint=models.UniqueConstraint(fields=('categoria', 'codigo'), name='inventario_tipo_codigo_unico_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='recurso',
            constraint=models.UniqueConstraint(fields=('estacion', 'codigo_interno'), name='inventario_recurso_codigo_unico_por_estacion'),
        ),
    ]
