# Generated by Django 6.1 on 2026-08-11 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio'), ('dado_baja', 'Dado de baja')], max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio'), ('dado_baja', 'Dado de baja')], max_length=20, verbose_name='estado nuevo')),
                ('disponibilidad_anterior', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('reservado', 'Reservado'), ('no_disponible', 'No disponible')], max_length=20, verbose_name='disponibilidad anterior')),
                ('disponibilidad_nueva', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('reservado', 'Reservado'), ('no_disponible', 'No disponible')], max_length=20, verbose_name='disponibilidad nueva')),
                ('motivo', models.CharField(max_length=255, verbose_name='motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='inventario.recurso', verbose_name='recurso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_recursos', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'historial de estado de recurso',
                'verbose_name_plural': 'historiales de estado de recursos',
                'ordering': ('-fecha_registro', '-pk'),
            },
        ),
    ]
