# Generated by Django 6.1 on 2026-08-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_historialestadorecurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporecurso',
            name='es_unidad_desplegable',
            field=models.BooleanField(default=False, help_text='Indica si los recursos de este tipo pueden despacharse a emergencias.', verbose_name='es unidad desplegable'),
        ),
    ]
