# Generated by Django 6.1 on 2026-08-11 02:48

from django.db import migrations


NOMBRES_GRUPOS = (
    "Administrador del sistema",
    "Responsable provincial",
    "Responsable institucional",
    "Responsable de estación",
    "Encargado de inventario",
    "Operador de consulta",
)


def crear_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for nombre in NOMBRES_GRUPOS:
        Group.objects.get_or_create(name=nombre)


def eliminar_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=NOMBRES_GRUPOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_estacion'),
    ]

    operations = [
        migrations.RunPython(crear_grupos, eliminar_grupos),
    ]
