"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Configuración local de desarrollo. En producción estas variables son obligatorias.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-only-do-not-use-in-production",
)

# El valor predeterminado solo es apropiado para desarrollo local.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "on")

if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "Defina DJANGO_SECRET_KEY con un valor propio antes de desplegar."
    )

def _lista_de_entorno(nombre):
    """Lee una variable separada por comas y devuelve sus valores sin espacios."""
    return [valor.strip() for valor in os.environ.get(nombre, "").split(",") if valor.strip()]

ALLOWED_HOSTS = _lista_de_entorno("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _lista_de_entorno("DJANGO_CSRF_TRUSTED_ORIGINS")

# Render publica el dominio asignado al servicio en esta variable, de modo que
# el despliegue funciona sin escribir el dominio a mano en la configuracion.
_DOMINIO_RENDER = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _DOMINIO_RENDER:
    ALLOWED_HOSTS.append(_DOMINIO_RENDER)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_DOMINIO_RENDER}")

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "Defina DJANGO_ALLOWED_HOSTS con los dominios que atendera el sitio."
    )

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Aplicaciones del sistema
    "core",
    "usuarios",
    "instituciones",
    "inventario",
    "operaciones",
    "emergencias",
    "dashboard",
    "mapas",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Después de la autenticación y de los mensajes: necesita request.user y
    # deja escribir avisos antes de redirigir.
    'usuarios.middleware.ExigirCambioDeClave',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "inventario.context_processors.acceso_catalogos",
                "operaciones.context_processors.acceso_capacidades",
                "usuarios.context_processors.acceso_usuarios",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYER_BACKEND = os.environ.get(
    "CHANNEL_LAYER_BACKEND", "memory" if DEBUG else "redis"
).lower()
if CHANNEL_LAYER_BACKEND == "memory":
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }
elif CHANNEL_LAYER_BACKEND == "redis":
    REDIS_URL = os.environ.get("REDIS_URL")
    if not REDIS_URL:
        raise ImproperlyConfigured(
            "Configure REDIS_URL cuando CHANNEL_LAYER_BACKEND=redis."
        )
    # Se usa la capa pub/sub y no channels_redis.core.RedisChannelLayer. Aquella
    # mantiene una suscripcion abierta, mientras que esta lee cada mensaje con
    # una operacion bloqueante contra Redis; cuando esa lectura excede su tiempo
    # de espera, la excepcion sube hasta el consumidor y corta la conexion del
    # cliente. El sistema solo usa group_add, group_discard y group_send, que la
    # capa pub/sub cubre por completo.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    raise ImproperlyConfigured(
        "CHANNEL_LAYER_BACKEND debe ser 'memory' o 'redis'."
    )

AUTH_USER_MODEL = "usuarios.Usuario"

LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "emergencias:lista"
LOGOUT_REDIRECT_URL = "usuarios:login"

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Un servicio administrado entrega la conexion en una sola URL. Cuando esta
# presente tiene prioridad; en desarrollo se siguen usando las variables sueltas
# y el archivo de secreto local, sin cambio alguno.
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    from urllib.parse import unquote, urlparse

    _conexion_url = urlparse(DATABASE_URL)
    _CONEXION = {
        "NAME": unquote(_conexion_url.path).lstrip("/"),
        "USER": unquote(_conexion_url.username or ""),
        "PASSWORD": unquote(_conexion_url.password or ""),
        "HOST": _conexion_url.hostname or "",
        "PORT": str(_conexion_url.port or 5432),
    }
else:
    POSTGRES_PASSWORD_FILE = BASE_DIR / "secrets" / "postgresql_password.txt"
    POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
    if not POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE.exists():
        POSTGRES_PASSWORD = POSTGRES_PASSWORD_FILE.read_text(encoding="utf-8").strip()
    if not POSTGRES_PASSWORD:
        raise ImproperlyConfigured(
            "Configure POSTGRES_PASSWORD, cree secrets/postgresql_password.txt "
            "o defina DATABASE_URL."
        )
    _CONEXION = {
        "NAME": os.environ.get("POSTGRES_DB", "bomberos_cotopaxi"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        **_CONEXION,
        "CONN_MAX_AGE": 60,
        # Las conexiones reutilizadas se verifican antes de usarse, porque un
        # servicio administrado puede cerrarlas por su cuenta.
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {"sslmode": os.environ.get("POSTGRES_SSLMODE", "prefer")},
    },
}

# Bibliotecas geoespaciales nativas que exige django.contrib.gis. No son
# paquetes de Python: django.contrib.gis.geos las carga con ctypes al importar
# el módulo, así que sin ellas la aplicación no arranca. Se resuelven en tres
# pasos, del más explícito al más circunstancial:
#
#   1. Las variables de entorno GDAL_LIBRARY_PATH y GEOS_LIBRARY_PATH.
#   2. Las bibliotecas que traen consigo los wheels de rasterio y shapely.
#      Es la vía que iguala desarrollo y producción, y la única disponible en
#      plataformas de despliegue que no permiten instalar paquetes del sistema.
#   3. La instalación local de QGIS, como respaldo para el equipo de desarrollo.
def _libreria_de_wheel(paquete, patrones):
    """Devuelve la biblioteca nativa incluida dentro del wheel de `paquete`.

    Los wheels de rasterio y shapely publican sus dependencias compiladas en un
    directorio `<paquete>.libs`. El nombre del archivo lleva un hash que cambia
    con cada versión, por eso se busca por patrón y no por nombre fijo.

    El paquete se importa, no basta con localizarlo. GDAL depende a su vez de
    otras bibliotecas que viajan en esa misma carpeta, entre ellas una copia
    privada de libcurl. En Linux esas vecinas solo se encuentran a través de la
    ruta de búsqueda que llevan grabada los módulos de extensión del paquete,
    de modo que importarlo es lo que las deja cargadas y disponibles. Abrir
    GDAL por su ruta absoluta sin ese paso previo falla con
    `cannot open shared object file` sobre una dependencia, no sobre GDAL.
    """
    import importlib

    try:
        modulo = importlib.import_module(paquete)
    except Exception:
        return None
    origen = getattr(modulo, "__file__", None)
    if not origen:
        return None
    carpeta = Path(origen).parent.parent / f"{paquete}.libs"
    for patron in patrones:
        encontradas = sorted(carpeta.glob(patron))
        if encontradas:
            return encontradas[0]
    return None

def _buscar_librerias_qgis():
    """Devuelve (gdal, geos) de la instalación de QGIS más reciente."""
    import re

    for base in (Path(r"C:\Program Files"), Path(r"C:\Program Files (x86)")):
        if not base.exists():
            continue
        instalaciones = sorted(
            base.glob("QGIS *"),
            key=lambda ruta: [
                int(parte) for parte in re.findall(r"\d+", ruta.name)
            ],
            reverse=True,
        )
        for instalacion in instalaciones:
            geos = instalacion / "bin" / "geos_c.dll"
            gdal = next(
                (
                    dll
                    for dll in sorted((instalacion / "bin").glob("gdal*.dll"))
                    if re.fullmatch(r"gdal\d+\.dll", dll.name)
                ),
                None,
            )
            if gdal and geos.exists():
                return gdal, geos
    return None, None

def _resolver_libreria(variable, paquete, patrones, respaldo):
    if os.environ.get(variable):
        return os.environ[variable]
    empaquetada = _libreria_de_wheel(paquete, patrones)
    if empaquetada is not None:
        return str(empaquetada)
    return str(respaldo) if respaldo else None

_GDAL_QGIS, _GEOS_QGIS = _buscar_librerias_qgis()

_GDAL_RESUELTA = _resolver_libreria(
    "GDAL_LIBRARY_PATH", "rasterio",
    ("libgdal-*.so*", "gdal-*.dll", "libgdal*.dylib"), _GDAL_QGIS,
)
_GEOS_RESUELTA = _resolver_libreria(
    "GEOS_LIBRARY_PATH", "shapely",
    ("libgeos_c-*.so*", "geos_c-*.dll", "libgeos_c*.dylib"), _GEOS_QGIS,
)

# Si ninguna vía dio resultado no se define el ajuste, para que Django
# conserve su propia búsqueda en las rutas del sistema y falle con su
# mensaje habitual en lugar de con una ruta inventada.
if _GDAL_RESUELTA:
    GDAL_LIBRARY_PATH = _GDAL_RESUELTA
if _GEOS_RESUELTA:
    GEOS_LIBRARY_PATH = _GEOS_RESUELTA

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise comprime los archivos recolectados. En produccion se usa ademas el
# manifiesto, que agrega un hash al nombre de cada archivo y hace innecesario
# versionarlos a mano en las plantillas.
#
# El valor predeterminado es el almacenamiento sin manifiesto por dos razones:
# el manifiesto obliga a ejecutar collectstatic antes que las pruebas, porque la
# suite corre con DEBUG=False y resolveria cada archivo contra un manifiesto que
# aun no existe en una copia recien clonada; y la lista de precarga del service
# worker enumera rutas sin hash, que ninguna pagina volveria a pedir.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": os.environ.get(
            "DJANGO_STATICFILES_BACKEND",
            "whitenoise.storage.CompressedStaticFilesStorage",
        ),
    },
}

# Seguridad del transporte. Solo se activa fuera de desarrollo, para no exigir
# HTTPS en el servidor local.
if not DEBUG:
    # El proxy de la plataforma termina el TLS y anuncia el esquema original.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Avisos de `check --deploy` revisados uno por uno y descartados con motivo:
    #
    # mail.E001  El sistema no envia correo. Django exige un backend SMTP en
    #            produccion, pero declarar uno sin servidor detras seria falso.
    #            Cuando exista notificacion por correo se definira
    #            DJANGO_EMAIL_BACKEND con SMTP y se retirara este silenciamiento.
    # security.W021  No se activa SECURE_HSTS_PRELOAD porque la lista de
    #            precarga de los navegadores solo admite dominios propios, no
    #            subdominios de la plataforma, y la inscripcion es dificil de
    #            revertir. Debe reconsiderarse al publicar un dominio propio.
    SILENCED_SYSTEM_CHECKS = ["mail.E001", "security.W021"]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# El sistema no envia correo todavia. Se deja configurable para que, cuando lo
# haga, baste con definir DJANGO_EMAIL_BACKEND y los datos del servidor.
MAILERS = {
    'default': {
        'BACKEND': os.environ.get(
            "DJANGO_EMAIL_BACKEND",
            "django.core.mail.backends.console.EmailBackend",
        ),
    },
}

# Configuracion de los archivos multimedia
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
