"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Configuración local de desarrollo. En producción estas variables son obligatorias.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-only-do-not-use-in-production",
)

# El valor predeterminado solo es apropiado para desarrollo local.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Aplicaciones del sistema
    "core",
    "usuarios",
    "instituciones",
    "inventario",
    "operaciones",
    "emergencias",
    "dashboard",
    "mapas",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "operaciones.context_processors.acceso_capacidades",
                "usuarios.context_processors.acceso_usuarios",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYER_BACKEND = os.environ.get(
    "CHANNEL_LAYER_BACKEND", "memory" if DEBUG else "redis"
).lower()
if CHANNEL_LAYER_BACKEND == "memory":
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }
elif CHANNEL_LAYER_BACKEND == "redis":
    REDIS_URL = os.environ.get("REDIS_URL")
    if not REDIS_URL:
        raise ImproperlyConfigured(
            "Configure REDIS_URL cuando CHANNEL_LAYER_BACKEND=redis."
        )
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    raise ImproperlyConfigured(
        "CHANNEL_LAYER_BACKEND debe ser 'memory' o 'redis'."
    )

AUTH_USER_MODEL = "usuarios.Usuario"

LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "emergencias:lista"
LOGOUT_REDIRECT_URL = "usuarios:login"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

POSTGRES_PASSWORD_FILE = BASE_DIR / "secrets" / "postgresql_password.txt"
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
if not POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE.exists():
    POSTGRES_PASSWORD = POSTGRES_PASSWORD_FILE.read_text(encoding="utf-8").strip()
if not POSTGRES_PASSWORD:
    raise ImproperlyConfigured(
        "Configure POSTGRES_PASSWORD o cree secrets/postgresql_password.txt."
    )

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("POSTGRES_DB", "bomberos_cotopaxi"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    },
}

# Librerías geoespaciales instaladas con QGIS en el equipo de desarrollo.
# Se detecta cualquier versión de QGIS presente para no depender de un número
# de versión fijo. En producción pueden definirse rutas diferentes mediante
# las variables de entorno GDAL_LIBRARY_PATH y GEOS_LIBRARY_PATH.
def _buscar_librerias_qgis():
    """Devuelve (gdal, geos) de la instalación de QGIS más reciente."""
    import re

    for base in (Path(r"C:\Program Files"), Path(r"C:\Program Files (x86)")):
        if not base.exists():
            continue
        instalaciones = sorted(
            base.glob("QGIS *"),
            key=lambda ruta: [
                int(parte) for parte in re.findall(r"\d+", ruta.name)
            ],
            reverse=True,
        )
        for instalacion in instalaciones:
            geos = instalacion / "bin" / "geos_c.dll"
            gdal = next(
                (
                    dll
                    for dll in sorted((instalacion / "bin").glob("gdal*.dll"))
                    if re.fullmatch(r"gdal\d+\.dll", dll.name)
                ),
                None,
            )
            if gdal and geos.exists():
                return gdal, geos
    return None, None


_GDAL_LOCAL, _GEOS_LOCAL = _buscar_librerias_qgis()
if os.environ.get("GDAL_LIBRARY_PATH"):
    GDAL_LIBRARY_PATH = os.environ["GDAL_LIBRARY_PATH"]
elif _GDAL_LOCAL:
    GDAL_LIBRARY_PATH = str(_GDAL_LOCAL)
if os.environ.get("GEOS_LIBRARY_PATH"):
    GEOS_LIBRARY_PATH = os.environ["GEOS_LIBRARY_PATH"]
elif _GEOS_LOCAL:
    GEOS_LIBRARY_PATH = str(_GEOS_LOCAL)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Configuracion de los archivos multimedia
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
