# Generated by Django 6.1 on 2026-08-11 03:10

import django.db.models.deletion
import operaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_institucional', models.CharField(max_length=50, verbose_name='código institucional')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='cédula')),
                ('nombres', models.CharField(max_length=150, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='apellidos')),
                ('rango', models.CharField(blank=True, max_length=100, verbose_name='rango')),
                ('cargo_operativo', models.CharField(blank=True, max_length=100, verbose_name='cargo operativo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('fecha_ingreso', models.DateField(validators=[operaciones.models.validar_fecha_no_futura], verbose_name='fecha de ingreso')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('descanso', 'Descanso'), ('licencia', 'Licencia'), ('no_disponible', 'No disponible')], default='disponible', max_length=20, verbose_name='disponibilidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_operativo', to='instituciones.estacion', verbose_name='estación')),
                ('usuario', models.OneToOneField(blank=True, help_text='La correspondencia entre la estación de esta cuenta y la del personal se validará en una etapa posterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_operativo', to=settings.AUTH_USER_MODEL, verbose_name='cuenta de usuario')),
            ],
            options={
                'verbose_name': 'personal operativo',
                'verbose_name_plural': 'personal operativo',
                'ordering': ('apellidos', 'nombres'),
                'constraints': [models.UniqueConstraint(fields=('estacion', 'codigo_institucional'), name='operaciones_personal_codigo_unico_por_estacion')],
            },
        ),
    ]
