# Generated by Django 6.1 on 2026-08-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'especialidad operativa',
                'verbose_name_plural': 'especialidades operativas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CalificacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('instructor', 'Instructor')], default='basico', max_length=15, verbose_name='nivel')),
                ('numero_certificado', models.CharField(blank=True, max_length=100, verbose_name='número de certificado')),
                ('entidad_emisora', models.CharField(blank=True, max_length=150, verbose_name='entidad emisora')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='operaciones.personaloperativo', verbose_name='personal operativo')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_personal', to='operaciones.especialidadoperativa', verbose_name='especialidad')),
            ],
            options={
                'verbose_name': 'calificación del personal',
                'verbose_name_plural': 'calificaciones del personal',
                'ordering': ('personal__apellidos', 'personal__nombres', 'especialidad__nombre'),
            },
        ),
        migrations.AddField(
            model_name='personaloperativo',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='personal_calificado', through='operaciones.CalificacionPersonal', to='operaciones.especialidadoperativa', verbose_name='especialidades'),
        ),
        migrations.AddConstraint(
            model_name='calificacionpersonal',
            constraint=models.UniqueConstraint(fields=('personal', 'especialidad'), name='operaciones_calificacion_especialidad_unica_por_personal'),
        ),
        migrations.AddConstraint(
            model_name='calificacionpersonal',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha_emision')), _connector='OR'), name='operaciones_calificacion_vencimiento_valido'),
        ),
    ]
