# Generated by Django 6.1 on 2026-08-11 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_historialestadorecurso'),
        ('operaciones', '0002_especialidadoperativa_calificacionpersonal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCapacidadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'tipo de capacidad operativa',
                'verbose_name_plural': 'tipos de capacidades operativas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RequisitoRecursoCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad mínima')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='obligatorio')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_capacidades', to='inventario.tiporecurso', verbose_name='tipo de recurso')),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_recursos', to='operaciones.tipocapacidadoperativa', verbose_name='capacidad operativa')),
            ],
            options={
                'verbose_name': 'requisito de recurso para capacidad',
                'verbose_name_plural': 'requisitos de recursos para capacidades',
                'ordering': ('capacidad__nombre', 'tipo_recurso__nombre'),
                'constraints': [models.UniqueConstraint(fields=('capacidad', 'tipo_recurso'), name='operaciones_requisito_recurso_unico_por_capacidad'), models.CheckConstraint(condition=models.Q(('cantidad_minima__gte', 1)), name='operaciones_requisito_recurso_cantidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='RequisitoPersonalCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_minimo', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('instructor', 'Instructor')], default='basico', max_length=15, verbose_name='nivel mínimo')),
                ('cantidad_minima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad mínima')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='obligatorio')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_capacidades', to='operaciones.especialidadoperativa', verbose_name='especialidad operativa')),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_personal', to='operaciones.tipocapacidadoperativa', verbose_name='capacidad operativa')),
            ],
            options={
                'verbose_name': 'requisito de personal para capacidad',
                'verbose_name_plural': 'requisitos de personal para capacidades',
                'ordering': ('capacidad__nombre', 'especialidad__nombre', 'nivel_minimo'),
                'constraints': [models.UniqueConstraint(fields=('capacidad', 'especialidad', 'nivel_minimo'), name='operaciones_requisito_personal_unico_por_capacidad'), models.CheckConstraint(condition=models.Q(('cantidad_minima__gte', 1)), name='operaciones_requisito_personal_cantidad_positiva')],
            },
        ),
    ]
