# Generated by Django 6.1 on 2026-08-11 05:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('operaciones', '0003_tipocapacidadoperativa_requisitorecursocapacidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCapacidadEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cumple', 'Cumple'), ('parcial', 'Cumplimiento parcial'), ('no_cumple', 'No cumple')], max_length=15, verbose_name='estado')),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='porcentaje de cumplimiento')),
                ('detalle_recursos', models.JSONField(default=list, verbose_name='detalle de recursos')),
                ('detalle_personal', models.JSONField(default=list, verbose_name='detalle de personal')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de evaluación')),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_estaciones', to='operaciones.tipocapacidadoperativa', verbose_name='capacidad operativa')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_capacidades', to='instituciones.estacion', verbose_name='estación')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_capacidades_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='evaluado por')),
            ],
            options={
                'verbose_name': 'evaluación de capacidad de estación',
                'verbose_name_plural': 'evaluaciones de capacidades de estaciones',
                'ordering': ('-fecha_evaluacion', '-pk'),
            },
        ),
    ]
