# Generated by Django 6.1 on 2026-08-11 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_evaluacioncapacidadestacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDisponibilidadPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad_anterior', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('descanso', 'Descanso'), ('licencia', 'Licencia'), ('no_disponible', 'No disponible')], max_length=20, verbose_name='disponibilidad anterior')),
                ('disponibilidad_nueva', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('descanso', 'Descanso'), ('licencia', 'Licencia'), ('no_disponible', 'No disponible')], max_length=20, verbose_name='disponibilidad nueva')),
                ('motivo', models.CharField(max_length=255, verbose_name='motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_disponibilidad', to='operaciones.personaloperativo', verbose_name='personal operativo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_disponibilidad_personal', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'historial de disponibilidad del personal',
                'verbose_name_plural': 'historiales de disponibilidad del personal',
                'ordering': ('-fecha_registro', '-pk'),
            },
        ),
    ]
