# Generated by Django 6.1 on 2026-08-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_historialdisponibilidadpersonal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calificacionpersonal',
            name='operaciones_calificacion_especialidad_unica_por_personal',
        ),
        migrations.RemoveConstraint(
            model_name='calificacionpersonal',
            name='operaciones_calificacion_vencimiento_valido',
        ),
        migrations.RemoveField(
            model_name='historialdisponibilidadpersonal',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='historialdisponibilidadpersonal',
            name='registrado_por',
        ),
        migrations.RemoveConstraint(
            model_name='personaloperativo',
            name='operaciones_personal_codigo_unico_por_estacion',
        ),
        migrations.RemoveConstraint(
            model_name='requisitopersonalcapacidad',
            name='operaciones_requisito_personal_unico_por_capacidad',
        ),
        migrations.RemoveConstraint(
            model_name='requisitopersonalcapacidad',
            name='operaciones_requisito_personal_cantidad_positiva',
        ),
        migrations.RemoveField(
            model_name='evaluacioncapacidadestacion',
            name='detalle_personal',
        ),
        migrations.RemoveField(
            model_name='calificacionpersonal',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='calificacionpersonal',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='calificacionpersonal',
            name='verificado_por',
        ),
        migrations.DeleteModel(
            name='HistorialDisponibilidadPersonal',
        ),
        migrations.RemoveField(
            model_name='personaloperativo',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='personaloperativo',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='personaloperativo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='requisitopersonalcapacidad',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='requisitopersonalcapacidad',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='CalificacionPersonal',
        ),
        migrations.DeleteModel(
            name='PersonalOperativo',
        ),
        migrations.DeleteModel(
            name='EspecialidadOperativa',
        ),
        migrations.DeleteModel(
            name='RequisitoPersonalCapacidad',
        ),
    ]
