# Generated by Django 6.1 on 2026-08-11 02:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'cantón',
                'verbose_name_plural': 'cantones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CuerpoBomberos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='sigla')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('sitio_web', models.URLField(blank=True, verbose_name='sitio web')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuerpos_bomberos', to='instituciones.canton', verbose_name='cantón')),
            ],
            options={
                'verbose_name': 'Cuerpo de Bomberos',
                'verbose_name_plural': 'Cuerpos de Bomberos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitud')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('cuerpo_bomberos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estaciones', to='instituciones.cuerpobomberos', verbose_name='Cuerpo de Bomberos')),
            ],
            options={
                'verbose_name': 'estación',
                'verbose_name_plural': 'estaciones',
                'ordering': ('cuerpo_bomberos__nombre', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('cuerpo_bomberos', 'codigo'), name='instituciones_estacion_codigo_unico_por_cuerpo')],
            },
        ),
    ]
