# Generated by Django 6.1 on 2026-08-11 16:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('inventario', '0003_tiporecurso_es_unidad_desplegable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('tipo_emergencia', models.CharField(max_length=120, verbose_name='tipo de emergencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='prioridad')),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('en_atencion', 'En atención'), ('controlada', 'Controlada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='reportada', max_length=15, verbose_name='estado')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora del reporte')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de cierre')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección o referencia')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('estacion_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias_responsables', to='instituciones.estacion', verbose_name='estación responsable')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'emergencia',
                'verbose_name_plural': 'emergencias',
                'ordering': ('-fecha_reporte', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DespliegueUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_ruta', 'En ruta'), ('en_sitio', 'En sitio'), ('retornando', 'Retornando'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='asignada', max_length=15, verbose_name='estado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asignación')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='fecha de salida')),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True, verbose_name='fecha de llegada')),
                ('fecha_retorno', models.DateTimeField(blank=True, null=True, verbose_name='fecha de retorno o finalización')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('despachado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_despachados', to=settings.AUTH_USER_MODEL, verbose_name='despachado por')),
                ('estacion_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_unidades', to='instituciones.estacion', verbose_name='estación de procedencia')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_emergencias', to='inventario.recurso', verbose_name='unidad')),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despliegues', to='emergencias.emergencia', verbose_name='emergencia')),
            ],
            options={
                'verbose_name': 'despliegue de unidad',
                'verbose_name_plural': 'despliegues de unidades',
                'ordering': ('-fecha_asignacion', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='emergencia',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__isnull', True), ('fecha_cierre__gte', models.F('fecha_reporte')), _connector='OR'), name='emergencias_cierre_no_anterior_reporte'),
        ),
        migrations.AddConstraint(
            model_name='despliegueunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('asignada', 'en_ruta', 'en_sitio', 'retornando'))), fields=('unidad',), name='emergencias_unidad_un_despliegue_activo'),
        ),
    ]
