# Generated by Django 6.1 on 2026-08-11 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitud')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precisión horizontal (m)')),
                ('velocidad', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='velocidad (m/s)')),
                ('rumbo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='rumbo (grados)')),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='altitud (m)')),
                ('fecha_dispositivo', models.DateTimeField(blank=True, null=True, verbose_name='fecha del dispositivo')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de recepción')),
                ('fuente', models.CharField(choices=[('navegador', 'Navegador web')], default='navegador', max_length=20, verbose_name='fuente')),
                ('despliegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='emergencias.despliegueunidad', verbose_name='despliegue')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posiciones_unidades_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='reportado por')),
            ],
            options={
                'verbose_name': 'posición de unidad',
                'verbose_name_plural': 'posiciones de unidades',
                'ordering': ('-fecha_recepcion', '-pk'),
                'indexes': [models.Index(fields=['despliegue', '-fecha_recepcion'], name='pos_despl_fecha_idx'), models.Index(fields=['-fecha_recepcion'], name='pos_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='pos_latitud_valida'), models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='pos_longitud_valida'), models.CheckConstraint(condition=models.Q(('precision__isnull', True), ('precision__gte', 0), _connector='OR'), name='pos_precision_valida'), models.CheckConstraint(condition=models.Q(('velocidad__isnull', True), ('velocidad__gte', 0), _connector='OR'), name='pos_velocidad_valida'), models.CheckConstraint(condition=models.Q(('rumbo__isnull', True), models.Q(('rumbo__gte', 0), ('rumbo__lte', 360)), _connector='OR'), name='pos_rumbo_valido')],
            },
        ),
    ]
