# Generated by Django 6.1 on 2026-08-12 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0003_posicionunidad_postgis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSCI211',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='número del formulario')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', max_length=12)),
                ('punto_registro', models.CharField(help_text='Ejemplo: Puesto de Comando, Base, Helibase o Área de Espera.', max_length=150, verbose_name='punto de registro')),
                ('preparado_por_nombre', models.CharField(blank=True, max_length=150, verbose_name='preparado por')),
                ('emergencia_codigo_emitido', models.CharField(blank=True, editable=False, max_length=30)),
                ('incidente_fecha_emitida', models.DateTimeField(blank=True, editable=False, null=True)),
                ('incidente_direccion_emitida', models.CharField(blank=True, editable=False, max_length=255)),
                ('institucion_emitida', models.CharField(blank=True, editable=False, max_length=150)),
                ('estacion_emitida', models.CharField(blank=True, editable=False, max_length=150)),
                ('coordenadas_emitidas', models.CharField(blank=True, editable=False, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sci211_creados', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formulario_sci_211', to='emergencias.emergencia', verbose_name='emergencia')),
                ('finalizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sci211_finalizados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sci211_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulario SCI-211',
                'verbose_name_plural': 'formularios SCI-211',
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='RegistroRecursoSCI211',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_por', models.CharField(max_length=150, verbose_name='solicitado por')),
                ('fecha_hora_solicitud', models.DateTimeField(verbose_name='fecha y hora de solicitud')),
                ('clase_recurso', models.CharField(max_length=120, verbose_name='clase de recurso')),
                ('tipo_recurso', models.CharField(blank=True, max_length=120, verbose_name='tipo de recurso')),
                ('fecha_hora_arribo', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de arribo')),
                ('institucion_procedencia', models.CharField(max_length=150, verbose_name='institución de procedencia')),
                ('matricula_identificacion', models.CharField(max_length=80, verbose_name='matrícula o identificación')),
                ('numero_personas', models.PositiveSmallIntegerField(default=1, verbose_name='número de personas')),
                ('estado_recurso', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('fuera_servicio', 'Fuera de servicio')], max_length=20)),
                ('ubicacion_recurso', models.CharField(blank=True, max_length=180, verbose_name='ubicación del recurso')),
                ('desmovilizado_por', models.CharField(blank=True, max_length=150, verbose_name='desmovilización autorizada por')),
                ('fecha_hora_desmovilizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=1500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('despliegue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_sci211', to='emergencias.despliegueunidad', verbose_name='despliegue de origen')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='emergencias.formulariosci211', verbose_name='formulario SCI-211')),
            ],
            options={
                'verbose_name': 'registro de recurso SCI-211',
                'verbose_name_plural': 'registros de recursos SCI-211',
                'ordering': ('orden', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('despliegue__isnull', False)), fields=('formulario', 'despliegue'), name='sci211_despliegue_unico_por_formulario')],
            },
        ),
    ]
