# Generated by Django 6.1 on 2026-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0004_formulariosci211_registrorecursosci211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariosci211',
            old_name='preparado_por_nombre',
            new_name='registrador_1',
        ),
        migrations.RenameField(
            model_name='registrorecursosci211',
            old_name='ubicacion_recurso',
            new_name='asignado_a',
        ),
        migrations.AddField(
            model_name='formulariosci211',
            name='incidente_nombre_emitido',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='formulariosci211',
            name='registrador_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre del registrador 2'),
        ),
        migrations.AddField(
            model_name='formulariosci211',
            name='registrador_3',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre del registrador 3'),
        ),
        migrations.AlterField(
            model_name='registrorecursosci211',
            name='asignado_a',
            field=models.CharField(blank=True, help_text='Ubicación geográfica o asignación actual del recurso.', max_length=180, verbose_name='asignado a'),
        ),
        migrations.AlterField(
            model_name='formulariosci211',
            name='registrador_1',
            field=models.CharField(max_length=150, verbose_name='nombre del registrador 1'),
        ),
    ]
