# Generated by Django 6.1 on 2026-08-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0006_formulariosci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariosci',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', max_length=12),
        ),
        migrations.AddField(
            model_name='formulariosci',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='formulariosci',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_sci_finalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulariosci',
            name='preparado_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='preparado por'),
        ),
    ]
