# Generated by Django 6.1 on 2026-08-31 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0009_registrorecurso_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegueunidad',
            name='responsable_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despliegues_conducidos', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la unidad'),
        ),
        migrations.AddField(
            model_name='registrorecursosci211',
            name='responsable_unidad',
            field=models.ForeignKey(blank=True, help_text='Quien va en la unidad. Podrá transmitir su ubicación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_sci_conducidos', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la unidad'),
        ),
    ]
