# Generated by Django 6.1 on 2026-09-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0010_despliegueunidad_responsable_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegueunidad',
            name='transmitiendo',
            field=models.BooleanField(default=False, verbose_name='transmitiendo ubicación'),
        ),
    ]
