# Generated by Django 6.1 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0011_despliegueunidad_transmitiendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorecursosci211',
            name='estado_recurso',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20),
        ),
    ]
